<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>nmp</string>
		<string>nmpinc</string>
		<string>md</string>
	</array>
	<key>name</key>
	<string>Nmp</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>#nmpRegion\(\s*?[cC]#\s*?\)</string>
			<key>end</key>
			<string>#nmpRegion\(\s*?c#\s*?\)</string>
			<key>name</key>
			<string>meta.regionblock.cs</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>source.cs</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(#define\(|#.define\()</string>
			<key>end</key>
			<string>(\))\s+$</string>
			<key>name</key>
			<string>variable.language.define.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>support.function.nmp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>none</string>
			<key>match</key>
			<string>#\.{0,1}(push[dD]ivert|pop[dD]ivert|saveDivert)\(.*?\)$</string>
			<key>name</key>
			<string>support.function.nmp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>keyword.other.nmp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#someName(...)</string>
			<key>match</key>
			<string>#\w+?\(.*?\)$</string>
			<key>name</key>
			<string>keyword.other.nmp</string>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.nmp</string>
				</dict>
			</dict>
			<key>comment</key>
			<string>#someName</string>
			<key>match</key>
			<string>(#\w+?)$</string>
			<key>name</key>
			<string>keyword.source.nmp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>`</string>
			<key>end</key>
			<string>'</string>
			<key>name</key>
			<string>string.quoted.other.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>\((#(defmacro|defarray|deflist)).*?\)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.nmp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\((#(endmacro|endarray|endlist))\)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.nmp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.function.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\(##&amp;)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.nmp</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(##\))</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.nmp</string>
				</dict>
			</dict>
			<key>name</key>
			<string>entity.name.function.nmp</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>match</key>
			<string>;{2,}.*$</string>
			<key>name</key>
			<string>comment.line.nmp</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>\(#\*</string>
			<key>end</key>
			<string>\*#\)</string>
			<key>name</key>
			<string>comment.block.nmp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.nmp</string>
	<key>uuid</key>
	<string>a400b095-4742-41f3-b8d2-7039fcc6ec10</string>
</dict>
</plist>
